package app.model;

public enum Condition {

    SEND_MESSAGE_TO_ADMIN,
    REQUEST_KEY,
    CREATE_AUDITORIUM,
    UPDATE_ID_AUDITORIUM,
    UPDATE_NAME_AUDITORIUM,
    UPDATE_TIME_REQUEST,
    UPDATE_ID_AUDITORIUM_REQUEST,
    CREATE_KEY,
    UPDATE_KEY,
    NONE

}
